import * as fs from 'fs';
import * as path from 'path';
import {PathResolver} from './PathResolver';
import type {EnvironmentService} from './EnvironmentService';
import type {EnvironmentsData} from '../types';
import {Logger} from '../utils/Logger';

export class PropertyService {
  private environmentService: EnvironmentService;

  public constructor(environmentService: EnvironmentService) {
    this.environmentService = environmentService;
  }

  public generateTypeScriptDefinitions(): void {
    const environments: EnvironmentsData =
      this.environmentService.loadEnvironments();
    const content: string = this.generateDefinitionContent(environments);

    const definitionFile: string = PathResolver.getEnvironmentsDefinitionFile();
    const definitionDir: string = path.dirname(definitionFile);

    if (!fs.existsSync(definitionDir)) {
      fs.mkdirSync(definitionDir, {recursive: true});
    }

    fs.writeFileSync(definitionFile, content, {encoding: 'utf-8'});
    Logger.success('TypeScript environment definitions generated');
  }

  private generateDefinitionContent(environments: EnvironmentsData): string {
    const envKeys: Array<string> = Object.keys(environments);
    const firstEnv: string = envKeys[0];
    const sampleEnv: Record<string, unknown> = environments[firstEnv];
    const properties: Array<string> = Object.keys(sampleEnv);

    let content: string = '// Auto-generated file - DO NOT EDIT MANUALLY\n';
    content += '// Generated by CLI PropertyService\n\n';

    content += 'declare module "@application" {\n';

    // Generate type for environment config
    content += '  export type EnvironmentConfig = {\n';
    content += '    id: string;\n';
    for (const prop of properties) {
      content += `    ${prop}: string;\n`;
    }
    content += '  };\n\n';

    // Generate constants
    content += `  export const ID: string;\n`;
    for (const prop of properties) {
      const constName: string = this.toUpperSnakeCase(prop);
      content += `  export const ${constName}: string;\n`;
    }

    content += '\n';

    // Generate all environments with prefixed constants
    for (const envKey of envKeys) {
      const ENV: string = envKey.toUpperCase();
      content += `  // ${ENV} Environment\n`;
      content += `  export const ${ENV}_ID: string;\n`;

      for (const prop of properties) {
        const constName: string = this.toUpperSnakeCase(prop);
        content += `  export const ${ENV}_${constName}: string;\n`;
      }

      content += '\n';
    }

    content += '}\n';

    return content;
  }

  private toUpperSnakeCase(str: string): string {
    return str
      .replace(/([A-Z])/g, '_$1')
      .toUpperCase()
      .replace(/^_/, '');
  }
}
